Repository bcgov-nr/action-test-and-analyse, pull requests merged in 2023-08, with the labels that each got.

#24 Bug: test stopped, add postgres service
  .github/workflows/unit-tests.yml
Labels: bug

#23 Bump SonarSource/sonarcloud-github-action from 1.8 to 2.0
  action.yml
Labels: dependencies

#25 feat: add triggers
  .github/workflows/unit-tests.yml
  .gitignore
  action.yml
Labels: enhancement

#28 Feat: optional non-default checkout branch
  README.md
  action.yml
Labels: enhancement

#20 make node_version a required field
  README.md
  action.yml
Labels: enhancement

#29 bug: drop ignored sonar comment token
  .github/workflows/unit-tests.yml
  README.md
  action.yml
Labels: bug

#30 docs: update readme for triggers
  README.md
Labels: documentation

#31 feat: deprecation messages and exits
  action.yml
Labels: enhancement

#32 Configure Renovate
  renovate.json
Labels: dependencies

#35 bug: missed triggers still firing
  action.yml
Labels: bug

#36 feat: param for triggers_event, default to pull_request
  .github/workflows/tests.yml
  README.md
  action.yml
Labels: enhancement

#38 ci: disable Dependabot for Renovate
  .github/dependabot.yml
Labels: dependencies
